version: "2"

services:
  example-site:
    image: nginx
    networks:
      - proxy-tier
    container_name: example-site
    volumes:
      - "$PWD/nginx/:/etc/nginx/conf.d"
      - "/location/of/website/repo:/usr/share/nginx/html"
    environment:
      - VIRTUAL_HOST=example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=info@example.com

networks:
  proxy-tier:
    external:
      name: nginx-proxy
